// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var buffers = buffers || {};

/**
 * @enum
 */
buffers.EntityUnion = {
  NONE: 0,
  PlayerBuffer: 1,
  GasCanBuffer: 2,
  WreckageBuffer: 3,
  LaunchpadBuffer: 4
};

/**
 * @enum
 */
buffers.MessageUnion = {
  NONE: 0,
  SnapshotBuffer: 1,
  InputPacketBuffer: 2,
  JoinDataBuffer: 3
};

/**
 * @constructor
 */
buffers.PositionBuffer = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {buffers.PositionBuffer}
 */
buffers.PositionBuffer.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
buffers.PositionBuffer.prototype.x = function() {
  return this.bb.readFloat32(this.bb_pos);
};

/**
 * @returns {number}
 */
buffers.PositionBuffer.prototype.y = function() {
  return this.bb.readFloat32(this.bb_pos + 4);
};

/**
 * @returns {number}
 */
buffers.PositionBuffer.prototype.rotation = function() {
  return this.bb.readFloat32(this.bb_pos + 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} x
 * @param {number} y
 * @param {number} rotation
 * @returns {flatbuffers.Offset}
 */
buffers.PositionBuffer.createPositionBuffer = function(builder, x, y, rotation) {
  builder.prep(4, 12);
  builder.writeFloat32(rotation);
  builder.writeFloat32(y);
  builder.writeFloat32(x);
  return builder.offset();
};

/**
 * @constructor
 */
buffers.StatsBuffer = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {buffers.StatsBuffer}
 */
buffers.StatsBuffer.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
buffers.StatsBuffer.prototype.xp = function() {
  return this.bb.readUint16(this.bb_pos);
};

/**
 * @returns {number}
 */
buffers.StatsBuffer.prototype.level = function() {
  return this.bb.readUint8(this.bb_pos + 2);
};

/**
 * @returns {number}
 */
buffers.StatsBuffer.prototype.health = function() {
  return this.bb.readUint16(this.bb_pos + 4);
};

/**
 * @returns {boolean}
 */
buffers.StatsBuffer.prototype.hurtFlag = function() {
  return !!this.bb.readInt8(this.bb_pos + 6);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} xp
 * @param {number} level
 * @param {number} health
 * @param {boolean} hurtFlag
 * @returns {flatbuffers.Offset}
 */
buffers.StatsBuffer.createStatsBuffer = function(builder, xp, level, health, hurtFlag) {
  builder.prep(2, 8);
  builder.pad(1);
  builder.writeInt8(+hurtFlag);
  builder.writeInt16(health);
  builder.pad(1);
  builder.writeInt8(level);
  builder.writeInt16(xp);
  return builder.offset();
};

/**
 * @constructor
 */
buffers.PlayerBuffer = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {buffers.PlayerBuffer}
 */
buffers.PlayerBuffer.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {buffers.PlayerBuffer=} obj
 * @returns {buffers.PlayerBuffer}
 */
buffers.PlayerBuffer.getRootAsPlayerBuffer = function(bb, obj) {
  return (obj || new buffers.PlayerBuffer).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
buffers.PlayerBuffer.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @param {buffers.PositionBuffer=} obj
 * @returns {buffers.PositionBuffer}
 */
buffers.PlayerBuffer.prototype.position = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new buffers.PositionBuffer).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {buffers.StatsBuffer=} obj
 * @returns {buffers.StatsBuffer}
 */
buffers.PlayerBuffer.prototype.stats = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new buffers.StatsBuffer).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
buffers.PlayerBuffer.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
buffers.PlayerBuffer.startPlayerBuffer = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} id
 */
buffers.PlayerBuffer.addId = function(builder, id) {
  builder.addFieldInt16(0, id, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} positionOffset
 */
buffers.PlayerBuffer.addPosition = function(builder, positionOffset) {
  builder.addFieldStruct(1, positionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} statsOffset
 */
buffers.PlayerBuffer.addStats = function(builder, statsOffset) {
  builder.addFieldStruct(2, statsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
buffers.PlayerBuffer.addName = function(builder, nameOffset) {
  builder.addFieldOffset(3, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
buffers.PlayerBuffer.endPlayerBuffer = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
buffers.GasCanBuffer = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {buffers.GasCanBuffer}
 */
buffers.GasCanBuffer.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {buffers.GasCanBuffer=} obj
 * @returns {buffers.GasCanBuffer}
 */
buffers.GasCanBuffer.getRootAsGasCanBuffer = function(bb, obj) {
  return (obj || new buffers.GasCanBuffer).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {buffers.PositionBuffer=} obj
 * @returns {buffers.PositionBuffer}
 */
buffers.GasCanBuffer.prototype.position = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new buffers.PositionBuffer).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {number}
 */
buffers.GasCanBuffer.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
buffers.GasCanBuffer.startGasCanBuffer = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} positionOffset
 */
buffers.GasCanBuffer.addPosition = function(builder, positionOffset) {
  builder.addFieldStruct(0, positionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} id
 */
buffers.GasCanBuffer.addId = function(builder, id) {
  builder.addFieldInt16(1, id, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
buffers.GasCanBuffer.endGasCanBuffer = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
buffers.LaunchpadBuffer = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {buffers.LaunchpadBuffer}
 */
buffers.LaunchpadBuffer.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {buffers.LaunchpadBuffer=} obj
 * @returns {buffers.LaunchpadBuffer}
 */
buffers.LaunchpadBuffer.getRootAsLaunchpadBuffer = function(bb, obj) {
  return (obj || new buffers.LaunchpadBuffer).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
buffers.LaunchpadBuffer.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @param {buffers.PositionBuffer=} obj
 * @returns {buffers.PositionBuffer}
 */
buffers.LaunchpadBuffer.prototype.position = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new buffers.PositionBuffer).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
buffers.LaunchpadBuffer.startLaunchpadBuffer = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} id
 */
buffers.LaunchpadBuffer.addId = function(builder, id) {
  builder.addFieldInt16(0, id, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} positionOffset
 */
buffers.LaunchpadBuffer.addPosition = function(builder, positionOffset) {
  builder.addFieldStruct(1, positionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
buffers.LaunchpadBuffer.endLaunchpadBuffer = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
buffers.WreckageBuffer = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {buffers.WreckageBuffer}
 */
buffers.WreckageBuffer.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {buffers.WreckageBuffer=} obj
 * @returns {buffers.WreckageBuffer}
 */
buffers.WreckageBuffer.getRootAsWreckageBuffer = function(bb, obj) {
  return (obj || new buffers.WreckageBuffer).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
buffers.WreckageBuffer.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @param {buffers.PositionBuffer=} obj
 * @returns {buffers.PositionBuffer}
 */
buffers.WreckageBuffer.prototype.position = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new buffers.PositionBuffer).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
buffers.WreckageBuffer.startWreckageBuffer = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} id
 */
buffers.WreckageBuffer.addId = function(builder, id) {
  builder.addFieldInt16(0, id, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} positionOffset
 */
buffers.WreckageBuffer.addPosition = function(builder, positionOffset) {
  builder.addFieldStruct(1, positionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
buffers.WreckageBuffer.endWreckageBuffer = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
buffers.EntityBuffer = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {buffers.EntityBuffer}
 */
buffers.EntityBuffer.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {buffers.EntityBuffer=} obj
 * @returns {buffers.EntityBuffer}
 */
buffers.EntityBuffer.getRootAsEntityBuffer = function(bb, obj) {
  return (obj || new buffers.EntityBuffer).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {buffers.EntityUnion}
 */
buffers.EntityBuffer.prototype.entityType = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {buffers.EntityUnion} */ (this.bb.readUint8(this.bb_pos + offset)) : buffers.EntityUnion.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
buffers.EntityBuffer.prototype.entity = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
buffers.EntityBuffer.startEntityBuffer = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {buffers.EntityUnion} entityType
 */
buffers.EntityBuffer.addEntityType = function(builder, entityType) {
  builder.addFieldInt8(0, entityType, buffers.EntityUnion.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} entityOffset
 */
buffers.EntityBuffer.addEntity = function(builder, entityOffset) {
  builder.addFieldOffset(1, entityOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
buffers.EntityBuffer.endEntityBuffer = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
buffers.InputPacketBuffer = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {buffers.InputPacketBuffer}
 */
buffers.InputPacketBuffer.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {buffers.InputPacketBuffer=} obj
 * @returns {buffers.InputPacketBuffer}
 */
buffers.InputPacketBuffer.getRootAsInputPacketBuffer = function(bb, obj) {
  return (obj || new buffers.InputPacketBuffer).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
buffers.InputPacketBuffer.prototype.mouseAngle = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt16(this.bb_pos + offset) : 0;
};

/**
 * @returns {boolean}
 */
buffers.InputPacketBuffer.prototype.slow = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {flatbuffers.Builder} builder
 */
buffers.InputPacketBuffer.startInputPacketBuffer = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} mouseAngle
 */
buffers.InputPacketBuffer.addMouseAngle = function(builder, mouseAngle) {
  builder.addFieldInt16(0, mouseAngle, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} slow
 */
buffers.InputPacketBuffer.addSlow = function(builder, slow) {
  builder.addFieldInt8(1, +slow, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
buffers.InputPacketBuffer.endInputPacketBuffer = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
buffers.JoinDataBuffer = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {buffers.JoinDataBuffer}
 */
buffers.JoinDataBuffer.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {buffers.JoinDataBuffer=} obj
 * @returns {buffers.JoinDataBuffer}
 */
buffers.JoinDataBuffer.getRootAsJoinDataBuffer = function(bb, obj) {
  return (obj || new buffers.JoinDataBuffer).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
buffers.JoinDataBuffer.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
buffers.JoinDataBuffer.startJoinDataBuffer = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
buffers.JoinDataBuffer.addName = function(builder, nameOffset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
buffers.JoinDataBuffer.endJoinDataBuffer = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
buffers.SnapshotBuffer = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {buffers.SnapshotBuffer}
 */
buffers.SnapshotBuffer.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {buffers.SnapshotBuffer=} obj
 * @returns {buffers.SnapshotBuffer}
 */
buffers.SnapshotBuffer.getRootAsSnapshotBuffer = function(bb, obj) {
  return (obj || new buffers.SnapshotBuffer).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {buffers.EntityBuffer=} obj
 * @returns {buffers.EntityBuffer}
 */
buffers.SnapshotBuffer.prototype.entities = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new buffers.EntityBuffer).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
buffers.SnapshotBuffer.prototype.entitiesLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {buffers.PlayerBuffer=} obj
 * @returns {buffers.PlayerBuffer}
 */
buffers.SnapshotBuffer.prototype.player = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new buffers.PlayerBuffer).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @returns {flatbuffers.Long}
 */
buffers.SnapshotBuffer.prototype.serverTimeMs = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
buffers.SnapshotBuffer.startSnapshotBuffer = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} entitiesOffset
 */
buffers.SnapshotBuffer.addEntities = function(builder, entitiesOffset) {
  builder.addFieldOffset(0, entitiesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
buffers.SnapshotBuffer.createEntitiesVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
buffers.SnapshotBuffer.startEntitiesVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} playerOffset
 */
buffers.SnapshotBuffer.addPlayer = function(builder, playerOffset) {
  builder.addFieldOffset(1, playerOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} serverTimeMs
 */
buffers.SnapshotBuffer.addServerTimeMs = function(builder, serverTimeMs) {
  builder.addFieldInt64(2, serverTimeMs, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
buffers.SnapshotBuffer.endSnapshotBuffer = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
buffers.MessageBuffer = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {buffers.MessageBuffer}
 */
buffers.MessageBuffer.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {buffers.MessageBuffer=} obj
 * @returns {buffers.MessageBuffer}
 */
buffers.MessageBuffer.getRootAsMessageBuffer = function(bb, obj) {
  return (obj || new buffers.MessageBuffer).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {buffers.MessageUnion}
 */
buffers.MessageBuffer.prototype.messageType = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {buffers.MessageUnion} */ (this.bb.readUint8(this.bb_pos + offset)) : buffers.MessageUnion.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
buffers.MessageBuffer.prototype.message = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
buffers.MessageBuffer.startMessageBuffer = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {buffers.MessageUnion} messageType
 */
buffers.MessageBuffer.addMessageType = function(builder, messageType) {
  builder.addFieldInt8(0, messageType, buffers.MessageUnion.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} messageOffset
 */
buffers.MessageBuffer.addMessage = function(builder, messageOffset) {
  builder.addFieldOffset(1, messageOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
buffers.MessageBuffer.endMessageBuffer = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
buffers.MessageBuffer.finishMessageBufferBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.buffers = buffers;
